name: Use Secrets
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confirm secret is available (masked)
        run: echo "Secret is available to the job"
        env:
          MY_API_KEY: ${{ secrets.SECRET_API_KEY }}
